name: Publish SDK package

on:
  push:
    branches:
      - release

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  publish-sdk:
    name: Build and publish SDK package
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish SDK
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

