name: Publish SDK package

on:
  push:
    branches:
      - release

jobs:
  test:
    name: Test SDK package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: package-lock.json
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

      - name: Install dependencies
        run: npm ci

      - name: Test SDK
        run: npm test

  publish-sdk:
    name: Build and publish SDK package
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish SDK
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

  # call the update workflow on github.com/smallhillcz/sdk to update the SDK package
  update-smhl-sdk:
    name: Update the package in Smallhill SDK
    uses: smallhillcz/sdk/.github/workflows/update.yml@master

